# Generated by Django 5.1.4 on 2024-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('nota_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='clientes',
            field=models.ManyToManyField(related_name='notas_fiscais', to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
