# Generated by Django 5.1.4 on 2024-12-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('nota_fiscal', '0002_alter_notafiscal_clientes_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
